name: Deploy Angular to Firebase Hosting

on:
  push:
    branches:
      - master # Trigger on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --configuration=production

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
